version: '3.5'

services:
  api:
    container_name: nest_api
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: "database"
      DB_PORT: 5432

  database:
    container_name: nest_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
